VOICEVOX/kanalizer

dataset/.gitignore
dataset/README.md
dataset/biome.jsonc
dataset/config.example.yml
dataset/config.schema.yml
dataset/package.json
dataset/pnpm-lock.yaml
dataset/src/config.ts
dataset/src/inference/gemini.ts
dataset/src/inference/index.ts
dataset/src/main.ts
dataset/src/random.ts
dataset/src/source/cmudict.ts
dataset/src/source/index.ts
dataset/src/tools/generateConfigSchema.ts
dataset/src/utils.ts
dataset/tsconfig.json

- bunからnodeに
- リファクタ
- .envからconfig.example.ymlに変更
- biomeを導入
をします。
（なし）
（なし）
（なし）

chore(dataset): 色々整備

---

dataset/config.example.yml
dataset/config.schema.yml
dataset/package.json
dataset/pnpm-lock.yaml
dataset/src/config.ts
dataset/src/inference/gemini.ts
dataset/src/inference/openai.ts
dataset/src/main.ts

OpenAI互換（OpenRouterなど）のAPIをたたけるようにします。
（なし）
（なし）
deepseek/deepseek-chat:freeで試しています、これが通ったらDraftを外す予定...

feat(dataset): OpenAI互換APIで読みの推論ができるように

---

dataset/src/inference/openai.ts
dataset/src/main.ts

- 起動時にprovider名を出す様にします。
- OpenRouterのエラーを認識するようにします。
（なし）
（なし）
（なし）

feat(dataset): 細かい改善

---

infer/crates/e2k-py/README.md
infer/crates/e2k-py/src/lib.rs
infer/crates/e2k-py/test_main.py
infer/crates/e2k-py/voicevox_e2k.pyi
infer/crates/e2k-rs/Cargo.toml
infer/crates/e2k-rs/README.md
infer/crates/e2k-rs/benches/benchmark.rs
infer/crates/e2k-rs/build.rs
infer/crates/e2k-rs/examples/repl.rs
infer/crates/e2k-rs/src/inference.rs
infer/crates/e2k-rs/src/lib.rs
infer/crates/e2k-rs/src/models.rs
infer/crates/e2k-rs/tests/test_main.rs

モデルを完全に埋め込みます。#13 の作り直し。
- closes: #12 
（なし）
（なし）

feat!(infer): モデルを埋め込む

---

.github/workflows/test_dataset.yml
.github/workflows/test_infer.yml
.github/workflows/test_train.yml

キャッシュを追加します（忘れてた...）
（なし）
（なし）
（なし）

ci(infer, dataset, train): キャッシュを追加

---

.github/workflows/merge_gatekeeper.yml

タイトルのとおりです。ファイル名はsnake_caseに合わせました。
- https://github.com/VOICEVOX/voicevox_project/issues/53

ci: merge-gatekeeperを導入

---

dataset/src/main.ts
dataset/src/utils.ts

タイトル通りです。
- close: #22 
（なし）
（なし）

chore(dataset): 推論段階で読みが有効かどうかチェックする

---

dataset/config.example.yml
dataset/config.schema.yml
dataset/src/config.ts
dataset/src/main.ts

タイトル通りです。
- ref: #24 
（なし）
（なし）

feat(dataset): バッチサイズを手動指定できるように

---

infer/crates/e2k-rs/build.rs

feat(infer): brotli圧縮をbuild.rsで行う

---

train/src/train.py

fix(train): 学習が落ちるのを修正

---

train/config/example.yml
train/src/config.py
train/src/train.py

- lrをconfigで指定できるようにします。
- Loss/evalをTensorboardにプロットするようにします。
（なし）
（なし）
（なし）

feat(train): 細かい機能追加

---

train/src/export.py

chore(train): export.pyの引数outputをそのまま使うように

---

dataset/config.test.yml
dataset/src/inference/dummy.ts
dataset/src/main.ts
dataset/src/utils.ts

推論機構をリファクタします。
具体的には、ジョブキューのように、Worker Threadを何個か用意してそれがキューを消化していく形にします。
（なし）
（なし）
（なし）

refactor(dataset): 推論周りをリファクタ

---

infer/Cargo.lock
infer/crates/e2k-rs/Cargo.toml
infer/crates/e2k-rs/build.rs

refactor(infer): anyhowをbuild.rsで使う

---

infer/Cargo.toml
infer/crates/kanalizer-py/Cargo.toml
infer/crates/kanalizer-rs/Cargo.toml

タイトル通りです。
これをやるとPyPIの検索欄とかに説明が出る。
（なし）
（なし）
（なし）

feat(infer): パッケージのdescriptionを追記

---

.github/workflows/build_and_deploy_infer.yml

タイトル通りです。
- ref: https://github.com/VOICEVOX/kanalizer/issues/41#issuecomment-2771764410
（なし）
（なし）

fix(infer): repository-urlの分岐を修正

---

infer/Cargo.toml
infer/crates/kanalizer-py/Cargo.toml
infer/crates/kanalizer-rs/Cargo.toml

repositoryをCargo.tomlに追加します。
これでPyPIのサイドバーとかにもリポジトリのリンクが出るはず。
（なし）
（なし）
（なし）

feat(infer): repositoryをCargo.tomlに追加

---

.github/workflows/build_and_deploy_infer.yml

fix(infer): working-directoryで怒られてたのを治す

---

MAINTENANCE.md

現在のPyPIの管理状況を追記します。
（なし）
（なし）
メンテナンスガイドライン、というかメンテナンス関連メモになりかけてる...

docs: PyPIの管理状況を追加

---

infer/Cargo.lock
infer/crates/kanalizer-py/kanalizer.pyi
infer/crates/kanalizer-py/src/lib.rs
infer/crates/kanalizer-py/test_main.py
infer/crates/kanalizer-rs/Cargo.toml
infer/crates/kanalizer-rs/benches/benchmark.rs
infer/crates/kanalizer-rs/examples/repl.rs
infer/crates/kanalizer-rs/src/error.rs
infer/crates/kanalizer-rs/src/inference.rs
infer/crates/kanalizer-rs/src/lib.rs
infer/crates/kanalizer-rs/tests/test_main.rs

feat(infer): 入力が有効か確認するようにする

---

infer/crates/kanalizer-py/kanalizer.pyi
infer/crates/kanalizer-py/src/lib.rs
infer/crates/kanalizer-rs/src/lib.rs

feat!(infer): 文字一覧の名称をINPUT/OUTPUT_CHARSにする

---

.github/workflows/test_dataset.yml

chore: setup-node、setup-pnpmを更新

---

train/src/constants.py

fix(train): SOS_IDX、EOS_IDXがズレていたのを修正

---

infer/Cargo.lock
infer/crates/kanalizer-rs/Cargo.toml
infer/crates/kanalizer-rs/build.rs

feat(infer): モデルのダウンロードを再試行する

---

infer/crates/kanalizer-py/kanalizer.pyi
infer/crates/kanalizer-py/pyproject.toml
infer/crates/kanalizer-py/python/kanalizer/__init__.py
infer/crates/kanalizer-py/python/kanalizer/_error.py
infer/crates/kanalizer-py/python/kanalizer/_rust.pyi
infer/crates/kanalizer-py/src/lib.rs
infer/crates/kanalizer-py/test_main.py
infer/crates/kanalizer-rs/src/error.rs
infer/crates/kanalizer-rs/src/inference.rs
infer/crates/kanalizer-rs/src/lib.rs
infer/crates/kanalizer-rs/tests/test_main.rs

feat!(infer): 推論が終了しなかったときにエラーを吐く

---

infer/crates/kanalizer-py/python/kanalizer/__init__.py
infer/crates/kanalizer-py/python/kanalizer/_error.py
infer/crates/kanalizer-py/src/converter.rs
infer/crates/kanalizer-py/src/lib.rs
infer/crates/kanalizer-py/test_main.py

Python側のエラーを細分化します。
（なし）
（なし）
（なし）

feat: Python側のエラーを細分化

---

train/src/train.py

再現性が減って結構危ないので、とりあえず固定にしてみました。
ref: https://github.com/VOICEVOX/kanalizer/issues/98

fix!(train): バッチサイズはどの条件でも固定にする

---

train/pyproject.toml

fix(train): trainコードのpyproject.tomlを現状に少し合わせる

---

train/config/example.yml

100じゃだいぶ足りなかったので。
ここがボトルネックになるようなら下げても良さそう。

feat(train): eval_max_wordsをnullに設定

---

infer/Cargo.toml
infer/crates/kanalizer-py/Cargo.toml
infer/crates/kanalizer-rs/Cargo.toml

inferのパッケージにlicenseを追加します。
（なし）
（なし）
（なし）

feat(infer): licenseの設定を追加

---

train/config/dummy.yml
train/config/example.yml
train/src/config.py
train/src/train.py
train/uv.lock

trainのデータセットを分割して一部で評価するようにします。
- closes: #107 
（なし）
（なし）

chore!(train): データセットを分割して一部で評価するようにする

---

train/src/infer.py

モデル以外を指定せずにinfer.pyを立ち上げるとreplが立ち上がるようにします。
（なし）
（なし）
（なし）

feat(train): infer.pyにreplモードを追加

---

train/src/config.py
train/src/train.py

configによってモデルの構造自体が変わるみたいなことがおきて設計がしんどいので、layernormを常に有効化します。
（なし）
（なし）
（なし）

chore!(train): layernormを常に有効にする

---

infer/crates/kanalizer-rs/build.rs
infer/crates/kanalizer-rs/src/inference.rs
infer/crates/kanalizer-rs/src/layers.rs
train/src/train.py

feat(infer): モデルをv5に更新

---

infer/crates/kanalizer-py/python/kanalizer/_rust.pyi

convertのmax_lengthの説明を更新します。
（なし）
（なし）
（なし）

docs(infer): max_lengthの説明を更新

---

infer/crates/kanalizer-py/python/kanalizer/_rust.pyi

Raises下のドキュメントを更新します。
（なし）
（なし）
codexくんをお試し中（ドキュメントの更新漏れがないかのチェック）

docs(infer): Raises下を更新
